### ISSUE TITLE
Unknown JSON RPC response error for `ACCOUNT/SET_BALANCE`

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#102]
Steps to reproduce:
1. Click on account

What expect:
1. Right balance value

What occur:
1. Nothing

From browser side:

![image](https://user-images.githubusercontent.com/39793/26841134-dcbe2014-4ae8-11e7-9139-096325ebb0f6.png)

From connector side:

```
TRACE:jsonrpc_core::io: Request: {"jsonrpc":"2.0","method":"eth_getBalance","params":["0x6a7cc99d37e28059306ce7f14ad99d671e7db6c0","latest"],"id":7}.
INFO:reqwest::client: Request: Post http://139.162.133.42:8545/
INFO:reqwest::response: Response: '200 OK' for http://139.162.133.42:8545/
DEBUG:jsonrpc_core::io: Response: Some("{\"jsonrpc\":\"2.0\",\"result\":\"0xd3a2c58d8e6588000\",\"id\":7}").
```

**Comment by dulanov** [comment]
![image](https://user-images.githubusercontent.com/39793/26841272-47e3fdfa-4ae9-11e7-9c5b-796d4258072e.png)

**Comment by dulanov** [comment]
@elaineo now, I don't see any errors, but by fact the send transaction buttion is disable and balance value looks strange:

![image](https://user-images.githubusercontent.com/39793/26854689-9c03efac-4b17-11e7-9bcb-97a82c112273.png)

**Comment by dulanov** [comment]
@elaineo We had stabilize testnet, did you can install all environment? Did you build latest `emerald-rs`?

**Comment by elaineo** [comment]
`send` is disabled because there is no Password, address, or amount. `Balance` looks like that because... I don't know how to make it look pretty yet ;) 

I will update my test environment, my `emerald-rs` has not been updated for a bit

**Comment by dulanov** [comment]
Ah, sorry for that, I think it works ;(
