### ISSUE TITLE
Need to show balance state while transaction in processing

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#115]
Wallet need to show some info about balance state of a `sender` after transaction  submition.
Right now wallet shows latest balance, till moment when transaction is processed by network.

**Comment by elaineo** [comment]
So pending transactions factor into a user's account balance? I don't really agree with this one. If a transaction has not been mined, the user can always resend it (https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#ethresend)

**Comment by dulanov** [comment]
You right, but probably better show something like - `123 (120 after process)`. Because, user sent some Ether and I think he want to see both numbers in some time - latest and pending.

**Comment by elaineo** [comment]
Okay. The wallet will calculate account balances (actual and pending) based on pending transactions.
related: https://github.com/ethereumproject/emerald-rs/issues/104

**Comment by elaineo** [comment]
this is addressed in #129. pending balance shows on account page. it is ugly right now.
