### ISSUE TITLE
Wallet need to disable `switch chain` functionality, when working with remote node

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#118]
Wallet need to hide section `switch chain` whenever user launched `emerald-rs` connector with options connect to remote client.
@elaineo, what info inside rpc do you need?

**Comment by elaineo** [comment]
Per the recent slack conversations, let's delay this one for after the release, because it may not be an `emerald-rs` interface in the future

**Comment by elaineo** [comment]
Dependency: #139

**Comment by elaineo** [comment]
i think this has been addressed in the updated UI
