### ISSUE TITLE
Retro 90s

### ISSUE THREAD

**Issue by Buzzlite** [ethereumproject/emerald-wallet#119]
Hi guys,

Would it be possible and better to add a progress bar with blocks and peers under rather than current design, in my opinion it looks very dated and 90s look,

what you guys think ?

**Comment by splix** [comment]
Hi, it's not really a design yet. It's just a layout, a location where UI elements should be located. A designer is working on nice graphical UI design. Just not yet ready

**Comment by Buzzlite** [comment]
Thanks for reply splix, no problem I undetstand and that is good news, just wanted to chime in as I thought it might be the final design.

thanks
