### ISSUE TITLE
Can't transfer token

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#13]
Allow to select token instead of Ether in transfer dialog

**Comment by elaineo** [comment]
@dulanov for "eth_call", do you want the data input already in hex format, like for `transfer(address,uint256)` it would look like: `0x70a082310000000000000000000000dA2384f1A7D80ca65469576228d268A5CacbfbE7`

or do you prefer `{data: '0x70a08231', address: 'dA2384f1A7D80ca65469576228d268A5CacbfbE7', value: 5}` and have the connector convert to hex?

**Comment by splix** [comment]
full data in hex, as currently supported by geth/parity api

**Comment by elaineo** [comment]
ok thanks, i will fix that in the `balanceOf` when displaying tokens for an account

**Comment by elaineo** [comment]
PR #33
