### ISSUE TITLE
handling after successful key import

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#131]
Should: 
- show confirmation of success/error
- redirect to account#show, 
- getBalance and update UI,  
- refresh app list of known accounts

Currently:
![screen shot 2017-06-14 at 13 47 43](https://user-images.githubusercontent.com/10228550/27149203-6bdb4c5c-5108-11e7-9fa6-1c9e0d688db5.png)

**Comment by elaineo** [comment]
merged #143
