### ISSUE TITLE
Improve layout for address screen

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#142]
![address](https://user-images.githubusercontent.com/48364/27209355-2f95f640-5219-11e7-907b-fe902cc28aab.png)

**Comment by elaineo** [comment]
Is this the same page as this one here, with the click-button for add ETC? https://github.com/ethereumproject/emerald-wallet/issues/127

**Comment by splix** [comment]
that's a current Address page, just little rearrangement

**Comment by elaineo** [comment]
Updated, Merged #143
