### ISSUE TITLE
User unable to switch to another chain

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#16]
User should have UI function to switch between testnet/mainnet

**Comment by elaineo** [comment]
Does this assume that the user is running two nodes simultaneously?

**Comment by splix** [comment]
Connector should restart node with new command line options

**Comment by elaineo** [comment]
okay. So this just issues switch node instruction to connector, something like `rpc.call('backend_switchNode', ['testnet'])`

**Comment by splix** [comment]
yes, like this. need to figure out actual method name and parameters, but let's use this as a mock

**Comment by elaineo** [comment]
merged #65
