### ISSUE TITLE
User unable to install custom contract

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#17]
Create a special screen with list of installed contracts, and a form to install one

- [x] Show installed contracts
- [x] Add ABI for existing contract on blockchain
- [x] Deploy new contract on blockchain

**Comment by elaineo** [comment]
@dulanov For `rpc('emerald_addContract', [{...}])`  do you want address, name, ABI?

**Comment by splix** [comment]
everything I think, it will store it as is. 

Right now we have:
```
{
  "version": "0.1",
  "address": "0x085fb4f24031eaedbc2b611aa528f22343eb52db",
  "name": "BitEther",
  "features": ["erc20"],
  "abi": [],
  "options": {
    "erc20": {}
  }
}
```

where:
 * `version` is contract's JSON format version
* `options` -> `erc20` can be overrides for erc20 for example (decimals, symbol, etc)

**Comment by elaineo** [comment]
Will add the following for "Deploy new Contract". (It seems odd to have them for simply installing a new contract, because ordinary users will probably be confused by version, features, options)

- [ ] Specify features, options, version
- [ ] validate ABI JSON
