### ISSUE TITLE
include emerald dependency with dist

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#173]
The wallet needs to have an `~/Library/Application Support/Emerald Wallet/bin/emerald` executable in order to work right (sign txs and manage accounts).

Options may include but are not limited to:
1. Include a static binary with the distribution
2. Implement a downloader like the one for geth
3. Run some shell scripts and 
  + Ensure rust is installed (ie `rustup`)
  + Use `cargo install emerald-cli` to grab install it and move/copy it to our appdata/bin/

My preference would probably be 2, 1, 3. 
  
Relates to #157, too.

**Comment by splix** [comment]
I prefer 1 for now. Because it's an additional point of failure, and we want to eliminate it for first release.

PS one of the big issues with current Mist that it fails to download & unpack Geth on some machines

**Comment by dulanov** [comment]
Related to https://github.com/ethereumproject/emerald-rs/issues/137.

**Comment by gagarin55** [comment]
It is fixed already, emerald binary included into distributive
