### ISSUE TITLE
account: balance is not setting

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#179]
![screen shot 2017-06-26 at 07 28 53](https://user-images.githubusercontent.com/10228550/27539228-57a9b7e0-5a41-11e7-9630-4ed47ae517f5.png)

**Comment by elaineo** [comment]
actually the balance is setting... the amount you have in that screenshot is 1000 wei, which is like 0.000000000000001 ETC, which is $0.00

**Comment by whilei** [comment]
yes, indeed -- figured that out shortly after and forgot to close this. thanks
