### ISSUE TITLE
sendTx: invalid sender

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#180]
![screen shot 2017-06-26 at 07 31 58](https://user-images.githubusercontent.com/10228550/27539307-a7651fc2-5a41-11e7-9342-3281ad7b4146.png)

possibly related to #179, if the error is because of an 'invalid balance' for the sender

**Comment by whilei** [comment]
don't think it is 'invalid balance' error, i was able to get one of those separately

**Comment by splix** [comment]
that's because of invalid `chain_id` most likely

**Comment by whilei** [comment]
rel https://github.com/ethereumproject/emerald-rs/issues/157

I'm going to add the `additional` params to the emerald rpc accountActions calls now

**Comment by r8d8** [comment]
Still reproducible on v0.2.0 (Linux)
