### ISSUE TITLE
Cold storage papers similar to EthAddress

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#187]
It should be helpful to support cold storage option, like https://ryepdx.github.io/ethaddress.org/

**Comment by dulanov** [comment]
![image](https://user-images.githubusercontent.com/39793/27596679-8bf3d5ce-5b60-11e7-9b3a-fe07f6ed3ad9.png)
![image](https://user-images.githubusercontent.com/39793/27596683-8eda4f5c-5b60-11e7-8b92-4d16fd170d8d.png)

**Comment by elaineo** [comment]
this is not for upcoming beta, correct?

**Comment by dulanov** [comment]
just idea, we spoke today a lot about this option in hangout daily conference.

**Comment by elaineo** [comment]
it is an important piece, regardless. i'l take it :)

**Comment by elaineo** [comment]
@dulanov will emerald-rs have an option for `emerald_exportAccount` that returns the decoded keystore file? Or should emerald-wallet decode the keystore file in the browser?

**Comment by dulanov** [comment]
@elaineo something like `emerald_stripAccount` new method?

**Comment by gagarin55** [comment]
Paper wallet was somehow implemented in https://github.com/ethereumproject/emerald-wallet/pull/310

We decode key file in wallet, not in emerald-vault.

Should we close this issue ?

**Comment by elaineo** [comment]
Yeah, lets close it.
