### ISSUE TITLE
Desktop Logo is hard to see. 

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/emerald-wallet#191]
![image](https://user-images.githubusercontent.com/20735086/27652738-c7ea8118-5c0a-11e7-85c8-820f97c95df8.png)

Desktop Logo is hard to see on dark backgrounds. Recommend a green outline or background for the logo.

**Comment by whilei** [comment]
![rounded_border](https://user-images.githubusercontent.com/10228550/27655059-aa896ac2-5c09-11e7-948e-ad7db99bc4a2.png)

what do you think about this? (rounded borders have transparent bg's, center white-ness is opaque)

**Comment by dulanov** [comment]
@ia Much much better for me!

**Comment by ChuckSRQ** [comment]
I like it. Works for me.

**Comment by whilei** [comment]
Sweet. I'm going to close this now until more designs come in or further notice.
