### ISSUE TITLE
Doesn't start with Windows Using Local Geth Node

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/emerald-wallet#201]
![image](https://user-images.githubusercontent.com/20735086/27678032-aa7246b2-5c81-11e7-912d-75c8b274cc37.png)

**Comment by dulanov** [comment]
Can you please also attach logs from `AppData/Roaming/EmeraldWallet`

**Comment by whilei** [comment]
@ChuckSRQ please check out this latest build -- it addresses this issue https://ci.appveyor.com/project/splix/emerald-wallet/build/130/artifacts
