### ISSUE TITLE
Unable to start full node Windows 7

### ISSUE THREAD

**Issue by Buzzlite** [ethereumproject/emerald-wallet#202]
![emerald2](https://user-images.githubusercontent.com/21130972/27685967-7088d7f8-5cc8-11e7-80f6-992e839b315c.PNG)

log
-------------------------------------------------------------------------
[2017-06-29 08:28:31:0428] [info] userData:  C:\Users\mine01\AppData\Roaming\EmeraldWallet
[2017-06-29 08:28:31:0434] [info] Chain: [type: none, chain: morden]
[2017-06-29 08:28:31:0455] [info] Starting Emerald...
[2017-06-29 08:28:31:0548] [info] use NONE Geth
[2017-06-29 08:28:31:0550] [info] Starting Emerald Connector... [chainId: 62]
[2017-06-29 08:28:31:0574] [info] Download geth.exe from https://github.com/ethereumproject/go-ethereum/releases/download/v3.5.0/geth-classic-win64-v3.5.0.zip to C:\Users\mine01\AppData\Local\Temp\download-geth.exe-2X4kRa/
[2017-06-29 08:28:33:0197] [info] Starting Emerald Wallet...
[2017-06-29 08:28:35:0190] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:28:35:0191] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:28:35:0192] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:28:35:0192] [error] Unknown network morden 62 none
[2017-06-29 08:28:39:0919] [error] Unable to download Geth Error: hash mismatch
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9194:110
    at Deferrals.exports.Deferrals.Deferrals._call (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18841:16)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18853:26
    at trampoline (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18819:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18851:16)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9189:32
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9190:15
    at Pair.verify_unpad_and_check_hash (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9200:15)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3560:25
    at _this.key_manager.pgp_check_not_expired.subkey_material (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3573:15)

[2017-06-29 08:32:57:0319] [info] Starting Emerald Wallet...
[2017-06-29 08:32:59:0316] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:32:59:0318] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:32:59:0318] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:32:59:0318] [error] Unknown network morden 62 none
[2017-06-29 08:33:32:0740] [info] Starting Emerald Wallet...
[2017-06-29 08:33:34:0735] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:33:34:0736] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:33:34:0736] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:33:34:0736] [error] Unknown network morden 62 none
[2017-06-29 08:37:28:0873] [info] Starting Emerald Wallet...
[2017-06-29 08:37:30:0867] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:37:30:0868] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:37:30:0868] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:37:30:0868] [error] Unknown network morden 62 none
[2017-06-29 08:40:11:0459] [info] Starting Emerald Wallet...
[2017-06-29 08:40:13:0454] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:40:13:0459] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:40:13:0459] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:40:13:0459] [error] Unknown network morden 62 none
[2017-06-29 08:40:28:0173] [info] Shutting down Local Connector
[2017-06-29 08:43:48:0017] [info] userData:  C:\Users\mine01\AppData\Roaming\EmeraldWallet
[2017-06-29 08:43:48:0023] [info] Chain: [type: none, chain: morden]
[2017-06-29 08:43:48:0040] [info] Starting Emerald...
[2017-06-29 08:43:48:0081] [info] use NONE Geth
[2017-06-29 08:43:48:0083] [info] Starting Emerald Connector... [chainId: 62]
[2017-06-29 08:43:48:0097] [info] Download geth.exe from https://github.com/ethereumproject/go-ethereum/releases/download/v3.5.0/geth-classic-win64-v3.5.0.zip to C:\Users\mine01\AppData\Local\Temp\download-geth.exe-sgVSbI/
[2017-06-29 08:43:49:0721] [info] Starting Emerald Wallet...
[2017-06-29 08:43:51:0717] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:43:51:0717] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:43:51:0718] [error] Could not match network type to a known type. Network type was: none
[2017-06-29 08:43:51:0718] [error] Unknown network morden 62 none
[2017-06-29 08:43:55:0910] [error] Unable to download Geth Error: hash mismatch
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9194:110
    at Deferrals.exports.Deferrals.Deferrals._call (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18841:16)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18853:26
    at trampoline (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18819:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:18851:16)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9189:32
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9190:15
    at Pair.verify_unpad_and_check_hash (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:9200:15)
    at C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3560:25
    at _this.key_manager.pgp_check_not_expired.subkey_material (C:\Users\mine01\AppData\Local\Programs\EmeraldWallet\resources\app.asar\electron\webpack-main.js:3573:15)

[2017-06-29 08:44:12:0749] [info] Shutting down Local Connector

**Comment by splix** [comment]
@Buzzlite can you try to launch it again?

**Comment by Buzzlite** [comment]
tried to launch again, here is the log

Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ index.js:33494
index.js:13104 i18next: languageChanged en-US
index.js:13104 i18next: initialized Object
index.js:108174 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
index.js:33494 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
printWarning @ index.js:33494
index.js:427 Warning: Failed prop type: Invalid prop `chain` of type `object` supplied to `Translate(Component)`, expected `string`.
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by Render)
    in div (created by Col)
    in Col (created by Render)
    in div (created by Row)
    in Row (created by Render)
    in div (created by Render)
    in Render (created by Connect(Render))
    in Connect(Render) (created by Unknown)
    in div (created by Col)
    in Col (created by Unknown)
    in div (created by Row)
    in Row (created by Unknown)
    in div (created by Grid)
    in Grid (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
printWarning @ index.js:427
index.js:427 Warning: Failed prop type: The prop `rpcType` is marked as required in `Translate(Component)`, but its value is `null`.
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by Render)
    in div (created by Col)
    in Col (created by Render)
    in div (created by Row)
    in Row (created by Render)
    in div (created by Render)
    in Render (created by Connect(Render))
    in Connect(Render) (created by Unknown)
    in div (created by Col)
    in Col (created by Unknown)
    in div (created by Row)
    in Row (created by Unknown)
    in div (created by Grid)
    in Grid (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
printWarning @ index.js:427
index.js:123229  action @ 19:28:45.972 LAUNCHER/CONFIG
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:123229  action @ 19:28:45.979 SCREEN/OPEN
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:59282 [19:28:45:0871] Starting Emerald Wallet...
index.js:59282 [19:28:45:0940] screen null
index.js:59282 [19:28:45:0981] screen welcome
index.js:123229  action @ 19:28:47.831 LAUNCHER/SERVICE_STATUS
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:123229  action @ 19:28:47.834 LAUNCHER/SERVICE_STATUS
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:123229  action @ 19:28:47.840 LAUNCHER/CHAIN
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:123229  action @ 19:28:47.865 NETWORK/SWITCH_CHAIN
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
3index.js:59282 [19:28:47:0866] Could not match network type to a known type. Network type was: none
(anonymous) @ index.js:59282
index.js:59282 [19:28:47:0868] Unknown network morden 62 none
(anonymous) @ index.js:59282
index.js:123229  action @ 19:28:48.918 LAUNCHER/CONFIG
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:123229  action @ 19:28:48.919 LAUNCHER/SETTINGS
index.js:123241  prev state Object
index.js:123245  action Object
index.js:123253  next state Object
index.js:59282 [19:28:54:0896] key is loaded a20208d4f6d4081c34742a182b6a1d7bfc7bbdef
index.js:59282 [19:28:54:0915] key is loaded b23dc6dc7634399484deb8a6f36487257419d94c
index.js:59282 [19:28:55:0248] Signed by PGP fingerprint b23dc6dc7634399484deb8a6f36487257419d94c
index.js:59282[19:28:55:0249] Unpack C:\Users\mine01\AppData\Local\Temp\download-geth.exe-NgX2w8\dest.zip
index.js:123229 action @ 19:28:55.250 LAUNCHER/MESSAGE
index.js:123241 prev state Object
index.js:123245 action Object
index.js:123253 next state Object
index.js:59282[19:28:55:0475] Finished extracting [ { deflated: 'geth.exe' } ]
index.js:123229 action @ 19:28:55.503 LAUNCHER/MESSAGE
index.js:123241 prev state Object
index.js:123245 action Object
index.js:123253 next state Object
index.js:59282[19:28:55:0499] Starting Geth... [network: morden, port: 8545]
index.js:59282[19:28:55:0607] Geth is ready
index.js:123229 action @ 19:28:55.609 LAUNCHER/MESSAGE
index.js:123241 prev state Object
index.js:123245 action Object
index.js:123253 next state Object
index.js:123229 action @ 19:28:55.613 LAUNCHER/SERVICE_STATUS
index.js:123241 prev state Object
index.js:123245 action Object
index.js:123253 next state Object

**Comment by whilei** [comment]
I think this commit ae966f4 may address the issue - I was able to recreate the problem and this fixes it for me

**Comment by whilei** [comment]
@Buzzlite hot off the press https://ci.appveyor.com/project/splix/emerald-wallet/build/130/artifacts

**Comment by Buzzlite** [comment]
thank you, downloading now to test :)

**Comment by Buzzlite** [comment]
getting places now, seems to just loop on the starting screen now after selecting full node, GETH starts successfully.

log
-----------------------------------------------------------------

index.js:33397 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ index.js:33397
lowPriorityWarning @ index.js:33416
get @ index.js:16831
__webpack_exports__.a @ index.js:48004
__webpack_require__ @ index.js:26
(anonymous) @ index.js:116458
__webpack_require__ @ index.js:26
validateFormat @ index.js:314
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:54676
__webpack_require__ @ index.js:26
(anonymous) @ index.js:112
(anonymous) @ index.js:115
index.js:13104 i18next: languageChanged en-US
index.js:13104 i18next: initialized Object {debug: true, initImmediate: true, ns: Array[1], defaultNS: "common", fallbackLng: Array[1]…}
index.js:108161 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
index.js:33397 Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
printWarning @ index.js:33397
lowPriorityWarning @ index.js:33416
get @ index.js:16839
(anonymous) @ index.js:31692
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:33821
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:49826
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:50497
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:52910
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:49595
__webpack_require__ @ index.js:26
Object.defineProperty.value @ index.js:54694
__webpack_require__ @ index.js:26
(anonymous) @ index.js:112
(anonymous) @ index.js:115
index.js:427 Warning: Failed prop type: Invalid prop `chain` of type `object` supplied to `Translate(Component)`, expected `string`.
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by Render)
    in div (created by Col)
    in Col (created by Render)
    in div (created by Row)
    in Row (created by Render)
    in div (created by Render)
    in Render (created by Connect(Render))
    in Connect(Render) (created by Unknown)
    in div (created by Col)
    in Col (created by Unknown)
    in div (created by Row)
    in Row (created by Unknown)
    in div (created by Grid)
    in Grid (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
printWarning @ index.js:427
warning @ index.js:451
checkReactTypeSpec @ index.js:118256
validatePropTypes @ index.js:48366
createElement @ index.js:48420
render @ index.js:47793
(anonymous) @ index.js:107978
measureLifeCyclePerf @ index.js:107258
_renderValidatedComponentWithoutOwnerOrContext @ index.js:107977
_renderValidatedComponent @ index.js:108004
performInitialMount @ index.js:107544
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountComponentIntoNode @ index.js:46322
perform @ index.js:21415
batchedMountComponentIntoNode @ index.js:46344
perform @ index.js:21415
batchedUpdates @ index.js:111184
batchedUpdates @ index.js:11728
_renderNewRootComponent @ index.js:46537
_renderSubtreeIntoContainer @ index.js:46619
render @ index.js:46640
start @ index.js:54737
(anonymous) @ index.html:12
index.js:427 Warning: Failed prop type: The prop `rpcType` is marked as required in `Translate(Component)`, but its value is `null`.
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by Render)
    in div (created by Col)
    in Col (created by Render)
    in div (created by Row)
    in Row (created by Render)
    in div (created by Render)
    in Render (created by Connect(Render))
    in Connect(Render) (created by Unknown)
    in div (created by Col)
    in Col (created by Unknown)
    in div (created by Row)
    in Row (created by Unknown)
    in div (created by Grid)
    in Grid (created by Unknown)
    in Unknown (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
printWarning @ index.js:427
warning @ index.js:451
checkReactTypeSpec @ index.js:118256
validatePropTypes @ index.js:48366
createElement @ index.js:48420
render @ index.js:47793
(anonymous) @ index.js:107978
measureLifeCyclePerf @ index.js:107258
_renderValidatedComponentWithoutOwnerOrContext @ index.js:107977
_renderValidatedComponent @ index.js:108004
performInitialMount @ index.js:107544
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountChildren @ index.js:111919
_createInitialChildren @ index.js:108907
mountComponent @ index.js:108726
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
performInitialMount @ index.js:107553
mountComponent @ index.js:107440
mountComponent @ index.js:16541
mountComponentIntoNode @ index.js:46322
perform @ index.js:21415
batchedMountComponentIntoNode @ index.js:46344
perform @ index.js:21415
batchedUpdates @ index.js:111184
batchedUpdates @ index.js:11728
_renderNewRootComponent @ index.js:46537
_renderSubtreeIntoContainer @ index.js:46619
render @ index.js:46640
start @ index.js:54737
(anonymous) @ index.html:12
index.js:123216  action @ 22:33:23.560 LAUNCHER/CONFIG
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "LAUNCHER/CONFIG", config: Object, launcherType: "electron"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123216  action @ 22:33:23.569 SCREEN/OPEN
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "SCREEN/OPEN", screen: "welcome", item: null}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:59269 [22:33:23:0450] Starting Emerald Wallet...
index.js:59269 [22:33:23:0521] screen null
index.js:59269 [22:33:23:0571] screen welcome
index.js:123216  action @ 22:33:25.397 LAUNCHER/SERVICE_STATUS
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "LAUNCHER/SERVICE_STATUS", mode: "not ready", service: "connector"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123216  action @ 22:33:25.401 LAUNCHER/SERVICE_STATUS
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "LAUNCHER/SERVICE_STATUS", mode: "ready", service: "geth"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123216  action @ 22:33:25.409 LAUNCHER/CHAIN
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "LAUNCHER/CHAIN", chain: "morden", chainId: 62, rpc: "local"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123216  action @ 22:33:25.412 NETWORK/SWITCH_CHAIN
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "NETWORK/SWITCH_CHAIN", network: "morden", id: 62, rpcType: "local"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123216  action @ 22:33:25.415 LAUNCHER/RPC
index.js:123228  prev state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:123232  action Object {type: "LAUNCHER/RPC", url: "http://localhost:8545"}
index.js:123240  next state Object {accounts: Object, addressBook: Object, tokens: Object, contracts: Object, screen: Object…}
index.js:59269 [22:33:25:0397] launcher listener:  type SERVICE_STATUS message { mode: 'not ready', service: 'connector' }
index.js:59269 [22:33:25:0412] launcher listener:  type SERVICE_STATUS message { mode: 'ready', service: 'geth' }
index.js:59269 [22:33:25:0418] launcher listener:  type CHAIN message { chain: 'morden', chainId: 62, rpc: 'local' }
index.js:59269 [22:33:25:0424] Found network: morden 62 local
index.js:59269 [22:33:25:0426] launcher listener:  type RPC message { url: 'http://localhost:8545' }
index.js:59269 [22:33:25:0429] Use RPC URL http://localhost:8545
![emeraldstart](https://user-images.githubusercontent.com/21130972/27711447-38292478-5d1b-11e7-8376-00cf9c8709bf.PNG)

**Comment by Buzzlite** [comment]
closing this, fixed in latest nightly
