### ISSUE TITLE
Alpha 0.1.0 JSON import failing

### ISSUE THREAD

**Issue by Buzzlite** [ethereumproject/emerald-wallet#207]
![json1](https://user-images.githubusercontent.com/21130972/27734298-2b184bd4-5d92-11e7-8233-74983f8d8eb3.PNG)

**Comment by whilei** [comment]
cc @dulanov @r8d8 This sounds like an [emerald-rs](https://github.com/ethereumproject/emerald-rs) issue

**Comment by dulanov** [comment]
@Buzzlite can you append some JSON examples, but without private data.

**Comment by r8d8** [comment]
yeap, without JSON data impossible to tell.

**Comment by r8d8** [comment]
@Buzzlite , does this JSON have "Crypto" section (starting from capital)?

**Comment by dulanov** [comment]
Exactly, the problem always because of `Crypto` field name, but should be `crypto`.

**Comment by Buzzlite** [comment]
here guys try this

**Comment by Buzzlite** [comment]
https://ufile.io/hjgg4

**Comment by splix** [comment]
maybe it's better to share sensitive data via a private chat? :)

**Comment by Buzzlite** [comment]
ah its ok, its just a wallet test :)

**Comment by splix** [comment]
ah, ok

**Comment by Buzzlite** [comment]
its a JSON created with classic ether wallet, but does not import, i guess its the same for all classic ether wallet JSONS,

**Comment by r8d8** [comment]
Yeap, Crypto from capital.

**Comment by r8d8** [comment]
We can't handle this stuff, because JSON deserializer requires 1:1 match

**Comment by Buzzlite** [comment]
ok so classic ether wallets will not be supported, gotcha

**Comment by r8d8** [comment]
you can just edit it by hand, at it will pass import

**Comment by Buzzlite** [comment]
ahh yes, i see, I edited it, imports fine now :) awesome, we can close this then as being fixed

**Comment by splix** [comment]
https://github.com/ethereumproject/emerald-rs/issues/174
