### ISSUE TITLE
Can not find private key

### ISSUE THREAD

**Issue by ChuckSRQ** [ethereumproject/emerald-wallet#212]
Can not find private key anywhere in latest windows build.

**Comment by jordanmack** [comment]
It is located in `C:\Users\<username>\AppData\Roaming\.emerald\mainnet\keystore`.

**Comment by dulanov** [comment]
Related to #187

**Comment by tt2105** [comment]
Hello. Created a new wallet etс. How to view the private key? This directory C:\Users\<username>\AppData\Roaming\.emerald\mainnet\keystore absent. ver2.2
