### ISSUE TITLE
Need Help Getting Coins Out of Wallet - Wallet Not Updating

### ISSUE THREAD

**Issue by RattitudeMining** [ethereumproject/emerald-wallet#22]
Hello ETC pros,

I have a wallet with a couple hundred ETC's in it and it's been stuck in there since less than a month after ETC was released.  However, didn't have time and couldn't find anywhere to find help, so here I am.  That said, I will give you as much information as I can.

I first put the coin in there on a previous version, which I don't remember the initial version but I had the very first ETC wallet and that's where I sent my coin to.  Ended up uninstalling and re-installing nearly every version up until 0.8.3 a few months after and ended up giving on it because I couldn't find any help.  Today,  I installed the latest mist version, still nothing.  I'm really stupid when it comes to wallets and Mist didn't help at all with the confusion but I can follow instructions, I know how to run a web server, I'm not computer illiterate.  I would like to get my coin out of this wallet and into something more stable, so I came here for assistance since the currency is ETC, this is where I should start troubleshooting.  The ETC experts are here, right?  I sure hope so.

Notes:
-Wallet been defective since Mist - 0.8.3
-Wallet is up to date (Mist - 0.8.9)
-Wallet is 7 months behind - Stuck on Block 2,111,708
-Which is when the wallet started having issues.
-Wallet ran for over a day and still not updating itself.
-Node counter fluctuates between 0 and 5 nodes.
-Ethereum Node in mist is showing Geth 1.5.9 (Go), which is the only option available other than none.
-Address with stuck coins: http://gastracker.io/addr/0x7cDE3FE3cDf5205418b7CE6581050C8341820B6D

I understand this may take a lot of time to fix whatever I did wrong, or are doing wrong, I understand, I just want access to my coins whilst I have an abundance of time.  Just hate having over a grand worth of coins stuck in a bum wallet; it is a real buzz kill.  However, if it's showing in the ETC block explorer, there should be some hope for me yet!

Didn't have much time until now either so, now's a good time for me to deal with this.

So long's we can get the wallet updating, it's all it needs, a bumpstart.

If this is in the wrong thread, please point my dumbass in the right direction.

Thank You!

-G

PS: I read around for information but for the more technical stuff, I prefer waiting and be guided rather than guide myself into doing the wrong things.

**Comment by elaineo** [comment]
If you have geth, you can run it with bootnodes: specify --bootnodes with the list of enodes here: https://github.com/paritytech/parity/issues/4717

**Comment by splix** [comment]
Geth 1.5.9 is outdated and incompatible with current chain. You need to upgrade Mist to v0.9.1 to get updated Geth, or you can run new Geth 3.3.0 binary manually and Mist will connect to it

**Comment by RattitudeMining** [comment]
Ok, I will go update Mist to 0.9.1 and will come back with results.

Sorry for delay, life happens to me sometimes and I had to deal with an emergency during the night in my mine and deal with some business this morning.  Hasn't happened all summer... then my computer went crashing to the floor for some reason.  It's been a total hell day to say the least.

**Comment by RattitudeMining** [comment]
I now get error:

Error running downloaded binary.
Checking network...

**Comment by RattitudeMining** [comment]
Opening old wallet yields this error: https://www.screencast.com/t/np24Ey5ROf3

**Comment by RattitudeMining** [comment]
Why was this thread closed?!?

Not like I'm resolved here!!! :(

Just going to do a restore, maybe I'll return to the old version, whatever I did there didn't work and go from there.  I have no idea what elaineo is talking about, just looks like a bunch of Chinese to me, not like this person did an effort to explain anything but had no problems closing my thread before I even done a reply.

**Comment by splix** [comment]
From a screen above it seems that you're using ETH Geth, which is not compatible with ETC. If you just want to transfer money once, you can use an online wallet, like https://www.myetherwallet.com/, you can import your private key from Geth into it.

Issue was closed because it doesn't look like it relates to Emerald Wallet project, because you're using different wallet implementation, so for Emerald Wallet project this bug is not reproducible.

**Comment by RattitudeMining** [comment]
I came here before I did not know where else to go :(
If I should be in a different thread, please point me there.

How do I get my private key from my current wallet?
This would be the best case scenario I think.

**Comment by splix** [comment]
You private keys should be under `%APPDATA%\Ethereum\keystore` directory. You can upload this files into MyEtherWallet (or other wallet). You'll need your password for a key (i.e. address) to use it

**Comment by RattitudeMining** [comment]
Awesome, thank you splix,  I will work on this now, will come back to update progress.

**Comment by RattitudeMining** [comment]
Every single attempt at doing anything with the keystore files has been a fail.
I'm not sure of my password but I tried every one I could think of have used, all to no avail.
I get a script error in my browser at every attempt and tried about 3 browsers too.
Is it normal that both files are the same size?  491bytes?

That said, what is parity?

I'm starting to try and wrap my head around elaino's file up there, seems like it's the last thing I can do here.... so I will likely ask many questions.

Guess I'll have to go back to square one but gained a better understanding.

**Comment by elaineo** [comment]
@RattitudeMining Is your filename something like "UTC--2017-03-20T03-03-53Z--{{address}}" ? what is the script error?

**Comment by RattitudeMining** [comment]
1- Yes, it is that filetype I was uploading to MyEtherWallet.com
2- Script Error: https://www.screencast.com/t/EL39HgLbaxtH

**Comment by elaineo** [comment]
um. Can you click on "Debug Script" to see the actual error?
(Or, can you do this on classicetherwallet.com ? i have a copy of that
source code at hand but not the myetherwallet one)

**Comment by RattitudeMining** [comment]
Attempting to get you this information, my browser froze but shown nothing I could screenshoot.

**Comment by RattitudeMining** [comment]
Still no progress.

**Comment by RattitudeMining** [comment]
I tried a dummy transaction to confirm password and I got the right one, so it's not a password problem.
Here's the dummy transaction record... it's even showing on the chain.
http://gastracker.io/tx/0xa8a8c90588830d8ebc05241431baaf3e864cffbd456e3b656b0349600a727a2a

I need to get my wallet to start connecting to nodes that will update the wallet itself, this is pretty much the best case scenario at this point.

**Comment by RattitudeMining** [comment]
I found this video that describes my problem but doesn't say if it's for ETC though, so please chime in.  I guess so long's I don't delete the key store folder, shouldn't be any issues, right?  This might even be a valid, legit way to fix this really easily, would like some ETC wallet experts to chime in on this before I actually do it.

https://www.youtube.com/watch?v=7YXyDw9Zeec

**Comment by RattitudeMining** [comment]
Ok, so boredom led me to doing what the guy did in the video; so here is what happened:

1- Copied the huge 8.8 GB file to my desktop
2- Deleted the chaindata folder
3- Restarted Ethereum

Now, the chain is downloading, or synchronizing with the network, blocks are being confirmed but I have to re-download the entire chain, which I can suspect will be a good 10GB's long.  My internet is capped daily at 2GB and I have other updates to do for other things that are also pressing matter.  This download could take up to two weeks.

Not only that, my coins have gone missing!  However, I can only assume they will come back once the blocks that contains them will show back up in my wallet once it reaches the point where the block that brought them to my wallet in the first place.

So please, do not keep your eyes off this thread as I will be updating progress regularly, just sucks I have such crappy and expensive internet.  

I even tried to synchronize the wallet with my high-latency internet to no avail so this may go faster than expected then but it's gonna cost me like $50 to download the chain.

**Comment by splix** [comment]
You really need to try with MyEthereWallet or classicetherwallet.com, because it doesn't require to download whole chain (and it's actually around 50Gb). You can try with different browser, I suggest Chrome.

**Comment by RattitudeMining** [comment]
Downloading with high-latency internet 1,6M Blocks remaining.

**Comment by splix** [comment]
Make sure you're using Classic Geth & Mist. Versions 3.2+ & 0.9.1 respectively, or you'll sync into wrong chain. Also, make sure you're using an SSD. And keep in mind that blocks 2.4M-2.5M are filled with hard to execute transactions and it takes 1-2 days to process this range on a modern computer with SSD

**Comment by RattitudeMining** [comment]
Update: Downloading chrome, put chain DL on hold due to costs and bandwidth high use, this is where I am getting my money's worth at 15kbps... downloading Chrome, if it works, would save me tons of time and bandwidth.  Connection needs a break, blocks barely move anymore (fast for 2GB then slow unlimited until the next day), I'll wait later tonight if this doesn't work, which, there is estimate there is a 50/50 chance that it does.

I know that some websites where only one browser really works well (gamer experience), I usually try to avoid websites that makes Google Chrome an exclusive to use the site's features.  In this case, corporate policy would state to temporarily download Chrome to get it done to get ours worth, even if just to try, there's value on the line and it is a possible scenario; it happens in other sites.

I'll see if my Java is up to date too.... would any other programs be required to run that script?

Still running Windows 7 SP1, so if anything later is required to even use that system, I probably can't use it anyways, due to OS conflicts.

**Comment by RattitudeMining** [comment]
VICTORY!!!

Transaction submitted. TX ID: 0xaa7a0df27f9272d48e8c17ec88601b3310a952d983832126af7b6d77085443f7
[View Transaction](http://gastracker.io/tx/0xaa7a0df27f9272d48e8c17ec88601b3310a952d983832126af7b6d77085443f7)

It was Chrome that did it, I don't believe it but I don't don't-believe it either.  Still not in my Polo wallet because I just did the tx but at least, the coin is out and didn't cost me an arm and a leg to do it.

I thank you very much for your help and patience with me into resolving this matter, I know I'm not an easy character to deal with but now, I can praise ETC rather than do the opposite.

This wasn't an easy task but... could have been easy if I would have used Chrome from the get go... they should put a sign "Script Requires Google Chrome" but in the end I'm glad of the outcome.

Will come back for a final comment once my coins are free from that wallet and in my Polo account.

**Comment by RattitudeMining** [comment]
All ETC coin is now officially in my Poloniex account and ready to do whatever I want with it.
Thank you ever so much for your assistance and devotion, I'm not likely to forget this any time soon.
Now I can shut people up who say ETC is a dead coin.

You've made me a very happy man today!

I think this is it, thread can be closed now, my problem is as resolved as it's going to get.

All the best with ETC, you gained my voice... and it's a powerful one.

Peace Out!! :)

:1st_place_medal:
