### ISSUE TITLE
Edit mode persists after changing address name and saving

### ISSUE THREAD

**Issue by jordanmack** [ethereumproject/emerald-wallet#225]
After changing the address name and clicking save, the application stays in edit mode. You must click cancel to go back. It is more intuitive to have the edit box disappear after clicking save.

![screenshot-1498889918](https://user-images.githubusercontent.com/37931/27759660-8e6de470-5dea-11e7-8036-799bc65618c8.png)

**Comment by gagarin55** [comment]
It fixed.
