### ISSUE TITLE
Address name should not be a required field

### ISSUE THREAD

**Issue by jordanmack** [ethereumproject/emerald-wallet#226]
Address name should not be a required field. After adding an address name you cannot remove it again. You should not be forced to have an address name.

![screenshot-1498889862](https://user-images.githubusercontent.com/37931/27759668-bb22e772-5dea-11e7-84c7-7b2b4ee02a56.png)

**Comment by gagarin55** [comment]
User can change account name later. BTW, we redesigned account generation wizard, you can check it in latest version at http://builds.etcdevteam.com
