### ISSUE TITLE
Dashboard and Home should have consistent naming if they are the same thing

### ISSUE THREAD

**Issue by jordanmack** [ethereumproject/emerald-wallet#227]
In the screenshot below, the menu references Home, and the blue link references Dashboard. They seem to go to the same place. It would be more intuitive to use the same name for both.

![screenshot-1498890123](https://user-images.githubusercontent.com/37931/27759673-0d4f1f48-5deb-11e7-9b44-b49d8b0a30ba.png)

**Comment by whilei** [comment]
Any preference on which name -- `Dashboard` or `Home`?

**Comment by splix** [comment]
A designer is working on a graphical design, so this will be changed anyway, when new design will come out

**Comment by srameshr** [comment]
@splix Is there a mobile web / app version development for the wallet?

**Comment by splix** [comment]
@srameshr Mobile version is an important goal and there is a plan to do that, but after few iterations of Desktop wallet. 

We have _Emerald Vault_ concept, which stores all private data and sign transactions, it allows to use wallet w/o full node and makes it usable on mobiles. So after we'll have stable release of desktop, we'll start working on mobile UI

**Comment by srameshr** [comment]
@splix Is _Emerald Vault_ open sourced or ready? Like an API or native mobile library or something, so that we can use that abstraction for transactions while just focusing on client mobile UI?

**Comment by splix** [comment]
@srameshr sure, everything is open source already. You can take a look at the code here https://github.com/ethereumproject/emerald-rs There maybe some terminology confusion, as it was initially called `emerald-rs` then `emerald-connector`, and now `emerald-vault` seems to be more accepted

**Comment by srameshr** [comment]
@splix The new design, will it be open sourced and will the designer consider doing a mobile version too?

**Comment by gagarin55** [comment]
@srameshr I think yes.

We have `Dashboard` term now. So, close this issue.
