### ISSUE TITLE
npm run start:web

### ISSUE THREAD

**Issue by d3orn** [ethereumproject/emerald-wallet#255]
Could you provide more info why it is not working?
I added the following to webpack.config.js
```
target: 'web',
node: {
  fs: "empty"
},
```
but now I am getting
Failed prop type: The prop `rpcType` is marked as required in `Translate(Component)`, but its value is `null`.

**Comment by gagarin55** [comment]
This is just warning, ignore it. But current implementation depends on electron even in `web` mode. Next errors in console will show you.
