### ISSUE TITLE
Appveyor script doesn't have VC++ Runtime environment dependencies

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#256]
Because of https://github.com/electron/electron/blob/master/script/create-dist.py#L91 and related to https://github.com/ethereumproject/emerald-rs/issues/173

**Comment by splix** [comment]
If we'll install in on CI server, does it mean that libraries will be included into package and it will not be required to ask our end-users to install VS2015 on their machines?

**Comment by dulanov** [comment]
I think so, because dlls will copy to dist by https://github.com/electron/electron/blob/master/script/create-dist.py#L91

**Comment by dulanov** [comment]
Look at `copy_vcruntime_binaries` method

**Comment by dulanov** [comment]
Probably this script only for electron, not for another projects based on top of electron, if so we should reuse it in our own project.

**Comment by dulanov** [comment]
Fixed by #257.
