### ISSUE TITLE
No option to use UUID instead of address to send transactions

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#27]
There is a possibility to find required keystore file by `address` (address is defined explicitly) or by `UUID v4` (the address is hidden).

**Comment by elaineo** [comment]
TODO:
- [ ] Add `name` to account map in `accountReducers`, so users can identify accounts by name
- [ ] `ipc("backend_importWallet", {"wallet": wallet})` will return `UUID v4` instead of `address` 
- [ ] Home page should list account name and (`address` OR `UUID v4` if `address` is not available)

**Comment by elaineo** [comment]
When getting account balance for a hidden address, connector should be able to interpret `rpc("eth_getBalance", [uuid])`

**Comment by r8d8** [comment]
@elaine, for the latest state of connector, we removed all functionality for hidden addresses. So, now operations for account processed by its address, no `uuid` option

**Comment by dulanov** [comment]
@elaineo we decided that `address` is mandatory field, if you want to hide your address, simply change it for on that you like, this field plays no role, we extract right address from private key.
