### ISSUE TITLE
Can't Send ETC Out Of Emerald Wallet

### ISSUE THREAD

**Issue by ScottD123** [ethereumproject/emerald-wallet#270]
Not really sure where to start. I downloaded Emerald Wallet about 2 weeks ago and have not been able to send anything out ever since I loaded the wallet with ETC. I enter target address, amount of ETC to send and my password, but it does nothing when I click the "Send" button. Any help or useful information would be greatly appreciated.

**Comment by elaineo** [comment]
@ScottD123 What OS are you using? Can you try the newest release? https://github.com/ethereumproject/emerald-wallet/releases

**Comment by ScottD123** [comment]
I am running Windows 7 Ultimate 64bit. I followed your link and performed the install but now the wallet is loading with a blank screen. Please let me know if there is anything else I can offer to help resolve the issue. (Screenshots, etc.)

**Comment by ScottD123** [comment]
![20317160_1498365573554586_401445289_o](https://user-images.githubusercontent.com/30245096/28495782-813a649a-6f1f-11e7-929a-8f49ed746711.jpg)

**Comment by splix** [comment]
@ScottD123 that's very strange bug, can't say what cal lead to this error, because it looks like JS wasn't compiled correctly. 

Anyway, it's already fixed in dev branch most likely, we'll make a next release soon. And if you want to try a dev build, just for testing, you can download it from here: http://builds.etcdevteam.com/

**Comment by ScottD123** [comment]
Dev build is up and running. Will try to execute a test send shortly. Thank you!

**Comment by splix** [comment]
@ScottD123 do you have this problem with new Beta version?

**Comment by ScottD123** [comment]
My apologies. I was out of town for a few weeks and I did not have time to test a transaction until now. As of this moment the transaction is pending - " In Queue "
 I will post again shortly with the results. Thank you.

**Comment by ScottD123** [comment]
Waited for about 3 hours and the transaction is stuck on Pending - " In Queue " 

Screenshots attached.
![20883761_1521077694616707_307774467_o](https://user-images.githubusercontent.com/30245096/29341689-9a249b5e-81eb-11e7-8b8e-86dc4e093216.jpg)

![20883128_1521076944616782_657747872_o](https://user-images.githubusercontent.com/30245096/29341691-9c1ba2cc-81eb-11e7-9f28-23405d923026.jpg)

**Comment by ScottD123** [comment]
Updated to Beta 0.4.0

Screenshot Attached.

![20907074_1521087997949010_2025397317_o](https://user-images.githubusercontent.com/30245096/29342020-d232fac0-81ed-11e7-888b-46e9e93ee590.jpg)

**Comment by ScottD123** [comment]
![20883902_1521091157948694_925642121_o](https://user-images.githubusercontent.com/30245096/29342100-72ac1b62-81ee-11e7-9779-542541886279.jpg)

**Comment by mongphp** [comment]
Same here, I created a transaction to send ETC out yesterday. But now it's still PENDING - IN QUEUE.

**Comment by splix** [comment]
what type of node do you use? a _local_ or _remote_?

**Comment by mongphp** [comment]
Hi @splix i'm using Remote

**Comment by ScottD123** [comment]
Reemote

**Comment by ScottD123** [comment]
@mongphp 
 I was able to work around whatever the issue may be by importing my emerald wallet JSON file to myetherwallet.com and executing my transaction from there. Worked great!

**Comment by splix** [comment]
@mongphp @ScottD123 thank you. It seems that it's an issue with `Nonce`, we had it before but seems to be not fully fixed yet. we'll track id down and fix

**Comment by Baltsar** [comment]
Same issue. Win 10 (64x).
Pressing Send doesn't resolve in anything. It doesn't say wrong password or right password.
