### ISSUE TITLE
Link to CLA gist

### ISSUE THREAD

**Issue by adrianbrink** [ethereumproject/emerald-wallet#277]
Could you give me the link to the original CLA gist used by the CLA bot?

**Comment by dulanov** [comment]
https://cla-assistant.io/ethereumproject/emerald-wallet

**Comment by adrianbrink** [comment]
I mean the gist.github.com url. I would like to reuse it for one of my other projects if that is okay?

**Comment by dulanov** [comment]
https://gist.github.com/splix/58d4ae5b9edd5727bd9d150780cda1e2

**Comment by adrianbrink** [comment]
Thank you
