### ISSUE TITLE
There are errors in js console on Windows

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#283]
Immediately from start, `Mainnet (Remote)`:

![image](https://user-images.githubusercontent.com/39793/28592257-b6560100-7188-11e7-8e35-6ab3611167a9.png)

![image](https://user-images.githubusercontent.com/39793/28592280-c6a33744-7188-11e7-8aa6-598da1a1eddf.png)

Nothing in `log.log`.

**Comment by splix** [comment]
fixed by [59ba7ad2f] and [b93836e95]
