### ISSUE TITLE
Impossible to select `Morden` network in settings on Windows

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#285]
![image](https://user-images.githubusercontent.com/39793/28592735-4281c14a-718a-11e7-8a51-78c71fec0ca6.png)

**Comment by dulanov** [comment]
Why we need it in settings, I mean "Network"?

**Comment by gagarin55** [comment]
It was initially in design mock up, should we remove it now ?

**Comment by gagarin55** [comment]
I've removed network selection from settings page and closing this issue
