### ISSUE TITLE
icon to copy address to clipboard: un-clickable

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#296]
![screen shot 2017-07-29 at 09 03 14](https://user-images.githubusercontent.com/10228550/28745389-f6e4fdbe-743c-11e7-8bf0-fedab99c2da0.png)

Want: clicking should copy address to clipboard
Got: clicking selects account for navigation

**Comment by gagarin55** [comment]
Yes, we need pay attention to this control

**Comment by gagarin55** [comment]
fixed
