### ISSUE TITLE
Test beta 0.4.0 beta 1. JavaScript error.

### ISSUE THREAD

**Issue by dancexm** [ethereumproject/emerald-wallet#305]
Thank you for the work done! Users really appreciate your work and are waiting for a stable version.
And now about the issue.
At first everything started and worked. I connected to a remote node. He created a purse, exported, enjoyed design (with the exception of some ergonomic inconveniences).
The second launch failed. Running with administrator rights did not succeed.
Win 10, ver. 1703, java ver. 8 upd. 131

![emer error](https://user-images.githubusercontent.com/15094722/28891956-50a4adec-77dd-11e7-8999-246e5d42fb2c.JPG)

**Comment by elaineo** [comment]
duplicate issue - combining this

**Comment by mateusreis** [comment]
New version (EmeraldWallet-mac-v0.4.13-98c3af1.dmg) still got the same error. 

![screenshot 2017-08-07 at 18 57 45](https://user-images.githubusercontent.com/934557/29047570-9f7fdc48-7ba2-11e7-94ae-e568fdc04363.jpg)
