### ISSUE TITLE
UI/syntax: the word 'wallet' is conflated

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#307]
The app reuses the word `wallet` in multiple, and to me, and conflated ways:

 - Emerald Wallet: the name of the app
 - Create/manage wallets (eg. `+ Wallets or Tokens`): where 'wallet' now used as a synonym for 'account' or 'address', which are singular entities; and Wallet conventionally means a collection of entities, eg. a couple of credit cards, a driver's license, some crumpled cash, a long-forgotten business card, your Blockbuster's rewards card...

## Solve proposal

- Keep the app name 'Emerald Wallet'.
- Instead of calling Ethereum Classic addresses "wallets", we should call
  them 'Accounts,' or, 'Addresses.' I prefer Addresses.

The reason I prefer Address
is because of the similarity between "user" (non-contract) addresses and
their strange robot/computer/corporation cousins: contracts. I don't think the
similarity between them should be obfuscated or downplayed, both for the
understanding of the layman and congruence for a wannabe DAPP dev. 
I think the word "Address" encourages this kind of ambiguity more than "Account."

Ambiguous etymological footnote:

When I think of the word Account, 
I think of a bank account, which is essentially a name linked to a number; 
it is not dynamic except for adding and subtracting.

However, when I think of an Address, 
I think of _knock-knock_ or _put-a-letter-in-the-mailbox_, and when you
_knock-knock_ on an Ethereum Address, you may be be "answered" by a real
person, OR, you might be answered by a very strange robot who handles the
business there. Ethereum is the land where corporations can begin to live up their
etymological namesake and actually handle the bills and respond to junk mail
and not only _be_ the business, but run it too.

Well that last part got a little rant-y. But anyways. 

Just a thought, of course open and happy for discussion.

**Comment by gagarin55** [comment]
I would prefer 'Account'. The reasons are:
1. Contract has Address too. There is two different action in app - create contract and create account.
2. When user press `create` they actually create 3 entities: Private key, Public key and Address derived from Public key
3. It's convenient for users who familiar with Ethereum Mist or other apps, which use term 'Account'

**Comment by whilei** [comment]
Right -- I think you make a good point; describing "user-addresses" as Accounts, and "contract-addresses" as Contracts; that makes sense to me.

👍
