### ISSUE TITLE
switch to mainnet [gastracker.io] fails invalid chain

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#312]
rel #310 

![mainnet-gastracker-switch](https://user-images.githubusercontent.com/10228550/29383229-40596712-8295-11e7-97f8-e9f1be10c24e.gif)

![screen shot 2017-08-16 at 15 09 04](https://user-images.githubusercontent.com/10228550/29383216-29749bfc-8295-11e7-83eb-2aa714d81a15.png)

**Comment by gagarin55** [comment]
This is because gastracker.io doesn't support `web3_clientVersion` method, so our wallet can't check chain and thinks that it is wrong.

@splix could you fix it ?

**Comment by splix** [comment]
ah, yes. will fix it, before release
