### ISSUE TITLE
Wallet not running

### ISSUE THREAD

**Issue by amontoya13** [ethereumproject/emerald-wallet#313]
Hi,

I'm having this issue when trying to run EmeraldWallet-mac-v0.4.22-50c8934.dmg on a MacOSX 10.12.5

Anyone else?

Best!

<img width="416" alt="screen shot 2017-08-16 at 4 45 37 pm" src="https://user-images.githubusercontent.com/31081347/29386617-5e439ef2-82a2-11e7-91fe-5b0c4bebfa1d.png">

**Comment by gagarin55** [comment]
Thank you for response, we will merge fixing PR in 1-2 days ! I will inform you.
