### ISSUE TITLE
Remove .VolumeIcons.icns

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#352]
![2017-10-27 0 30 33](https://user-images.githubusercontent.com/48364/32070452-348f16a6-baae-11e7-85ae-028c0c074fde.png)

A folder with something, top left corner

**Comment by whilei** [comment]
just a note for a possible fix, JetBrains/Gogland uses sneaky default window sizing (where the window is originally sized to be just as big as the background image)
![screen shot 2017-10-27 at 09 07 02](https://user-images.githubusercontent.com/10228550/32108233-a989970e-baf6-11e7-941a-5ff993e4980b.png)
