### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#395]
Emerald Wallet logo in SVG: [emerald-wallet-logo-svg.zip](https://github.com/ethereumproject/emerald-wallet/files/1532002/emerald-wallet-logo-svg.zip)

![etc emerald medium](https://user-images.githubusercontent.com/48364/33618255-04deb274-d9b0-11e7-82c2-b86f59da326f.png)

**Comment by splix** [comment]
I think it's for RC2, late for now

**Comment by whilei** [comment]
just for consideration

![etc emerald flat v2](https://user-images.githubusercontent.com/10228550/33621376-2228fc7c-d9b0-11e7-9811-15f740a8aaf9.png)
