### ISSUE TITLE
no screen to generate account

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#4]
Display a new screen after click on "generate new account", with fields:
* account name (optional)
* password
* password confirmation

On click "Generate" send it to the Connector and display resulting account id on same screen and "done" button (returns to main screen)

**Comment by elaineo** [comment]
Question about account management -- 

Is the goal to have everything managed by the node via IPC (`web3.personal.newAccount`) like Mist? It looks like we are using `rpc("eth_accounts", [])` to fetch a list of user accounts from the node, but from the Classic Wallet documentation it seems like the Connector will be storing account info.

**Comment by dulanov** [comment]
I will return all account related info directly from connector instead of redirect these RPC calls to client (prity, geth). I work on that, it's not done.

**Comment by elaineo** [comment]
ok thanks, just wanted to make sure i understood what was going on.

**Comment by dulanov** [comment]
We have implemented simple mediator or a proxy, which main task to resend all RPC calls futher to client, just to have a working wallet prototype ;)

Related issue for emerald connector - [No support for keystore files (UTC / JSON) encrypted with a passphrase](https://github.com/ethereumproject/emerald-rs/issues/15)

**Comment by elaineo** [comment]
PR opened #19
