### ISSUE TITLE
UI/link: after successful tx 

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#403]
Currently after send a successful tx the nearest visible link is:
![screen shot 2017-12-08 at 11 19 31](https://user-images.githubusercontent.com/10228550/33777365-1da98bce-dc0a-11e7-8011-7d062331c0fe.png)

Seems like `Repeat` a transaction is an infrequently used and not-to-be-encouraged action... would rather have a link to `View Transaction History`, with, if necessary, a button for repeating a transaction possibly within the transaction history UI.

**Comment by j-chimienti** [comment]
Can I attempt to fix?

**Comment by gagarin55** [comment]
`Repeat` functionality should be fixed according to https://github.com/ethereumproject/emerald-wallet/issues/343
