### ISSUE TITLE
UI: notification for address->clipboard copy status

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#407]
I clicked it... did it copy to clipboard? Did it fail? Have to paste to find out...

![emerald-copied-notification](https://user-images.githubusercontent.com/10228550/33778330-d0f74a88-dc0d-11e7-8da3-7476e64c07f5.gif)

**Comment by shanejonas** [comment]
fixed in https://github.com/ethereumproject/emerald-js-ui/pull/9
