### ISSUE TITLE
save  button 

### ISSUE THREAD

**Issue by MegoBasha** [ethereumproject/emerald-wallet#410]
1- 
The save  button doesn't bring back the main screen 
2-
the reload choice tacks time, so reopening it is more effective.

**Comment by TomaszWaszczyk** [comment]
Can I solve it?

**Comment by gagarin55** [comment]
This report not clear for me at all, should we close it ?

**Comment by MegoBasha** [comment]
ok, and thanks :)

**Comment by MegoBasha** [comment]
when i press the save button the main screen doesn't show back again
but it is ok to close it
many thanks
