### ISSUE TITLE
No passphrase when calling the `eth_sendTransaction`

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#42]
Now we should extract wallet data on every request, not permanently ('unlock' feature), therefore we need also a wallet passphrase.

**Comment by dulanov** [comment]
@splix Should we hide the password in logs, it can be not so simple?

**Comment by dulanov** [comment]
For example we can add it similar to https://github.com/paritytech/parity/wiki/JSONRPC-personal-module#personal_sendtransaction

**Comment by dulanov** [comment]
@splix we have three possibilities: just add a password as additional parameter to JSON, use HTTP POST header, or HTTP POST Authorization-Header?

**Comment by dulanov** [comment]
[HTTP Authentication: Basic and Digest Access Authentication](https://tools.ietf.org/html/rfc2617)

**Comment by dulanov** [comment]
But another way to 1. generate session secret key between wallet and connector and 2. use `X-KeyHmac` to encode passphrase.

**Comment by dulanov** [comment]
@elaineo can you please add a new input field for passphrase and include it in JSON RPC request as  `X-Passphrase` http header in base64 encodded format?

**Comment by splix** [comment]
@dulanov maybe it's better to reuse standard `Authorization` header?

**Comment by elaineo** [comment]
@splix I think that would be preferable too

**Comment by elaineo** [comment]
PR #44

**Comment by dulanov** [comment]
CORS support both variant - in preflight request (OPTION) we can return which HTTP Headers is suported by `Access-Control-Allow-Headers` or by `Access-Control-Allow-Credentials: true` declare basic authentification, so i will try to patch `jsonrpc` to return that attribute (`Access-Control-Allow-Credentials: true`) for CORS preflight request, details you can find (here)[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS].

**Comment by dulanov** [comment]
An opened issue in jsonrpc crate - https://github.com/paritytech/jsonrpc/issues/114

**Comment by dulanov** [comment]
@elaineo that issue is actual only for emerald-rs, not for wallet ;)
