### ISSUE TITLE
Wallet passphrases are sended as plain text

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#43]
My proposal it to introduce a secret session phrase and share it between wallet and connector.
Connector can take it from a file restricted with `-rw------- (400)` together with KDF (key-derivation function) details.

For every `eth_sendTransaction` request we can use `X-Session-Key` header to encrypt digest of message together with wallet's passphrase: `initialization vector (16 bytes) | encrypted text | hmac (32 bytes)`.

Should fix security hole introduced by #42.

**Comment by dulanov** [comment]
1. Receive session key - `session_phrase =KDF> session_key (32 bytes)`
2. Calculate request params hash - `json_params =keccak256> json_hash`
3. Verify data integrity & authentification - `(json_hash, session_text, session_key) =keccak256> hmac`
4. Decrypt wallet passphrase - `session_text =aes-128-ctr> account_passphrase`

**Comment by dulanov** [comment]
This proporsal has drawbacks - multiple cycles for encryption and decryption, it can bee three times slowly compared to just send `passphrase` as plain text.

**Comment by splix** [comment]
connector can publish own _Public Key_ to send sensitive data to it

**Comment by dulanov** [comment]
or better not to reinvent the wheel and take something like [Salted Challenge Response HTTP Authentication Mechanism](https://tools.ietf.org/html/rfc7804)

**Comment by dulanov** [comment]
As another alternative - [AWS Signature Version 4](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html).

**Comment by dulanov** [comment]
We will integrate `emerald-rs` into wallet directly via ffi, not needed any more.
