### ISSUE TITLE
New desktop header

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#437]
![header_green](https://user-images.githubusercontent.com/48364/34950881-a6510f0e-fa3e-11e7-99ca-c3b458792555.png)

Fullwidth panel, without logo. Title on left side, everything else on right side. Look more desktop friendly and less messy

**Comment by gagarin55** [comment]
@splix, we need Ethereum Classic logo icon same style as following icons.

![image](https://user-images.githubusercontent.com/18405789/35685899-04909e78-077c-11e8-80c6-af2669e88bca.png)
