### ISSUE TITLE
Mainnet (gastracker.io) wallet issue

### ISSUE THREAD

**Issue by iahawkins** [ethereumproject/emerald-wallet#442]
On the other selections like mainnet and mainnet (epool.io) my balance doesn't show up. Only when set to gastracker.io do I see a balance unfortunately this makes it load endlessly. This is also an issue when I leave the wallet set to load gastracker.io and I reboot the wallet. The opening screen is frozen loading. 

Any help would be much appreciated and thank you for this wonderful project!

**Comment by gagarin55** [comment]
When you chose **Mainnet** you have to wait for a while to sync full blockchain locally
Mainnet(epool.io) is remote endpoint which overloaded most of time, gastracker.io much better but still there is no guarantees.

**Comment by PandaHanda** [comment]
This is a problem for me to. Mainet is only at 709453 blocks and it has been about a week. Gastracker.io isn't even loading for me, even after a day. Is there anyway to update syncing manually. So far this is the worst experience I have ever had trying to get a wallet to sync. For a week to go by and not even be close to syncing is insane.

**Comment by iahawkins** [comment]
Fixed with latest update!
