### ISSUE TITLE
can't install dependency Emerald

### ISSUE THREAD

**Issue by caochao** [ethereumproject/emerald-wallet#454]
when i execute ./dependencies.sh, everything seens ok but got an error lastly.
![qq20180126-124521](https://user-images.githubusercontent.com/1911170/35425656-021e6076-0222-11e8-8ede-148347ea52a6.png)
pls tell me how to solve it, thx
platform is mac osx
node version is v6.0.0

**Comment by gagarin55** [comment]
Please, wait for a while, we will fix it

**Comment by gagarin55** [comment]
Fixed in https://github.com/ethereumproject/emerald-wallet/pull/455
