### ISSUE TITLE
Funds not appearing - NOT CLOSED NOT SOLVED

### ISSUE THREAD

**Issue by PandaHanda** [ethereumproject/emerald-wallet#457]
Hi everyone,

First off thanks for your hard work putting the wallet together!

I'm running a mac, with emerald wallet 0.6.0 1122.

I sent ETC to the wallet a few days ago from Bittrex and Binance, neither deposit is appearing. I don't know if the wallet is synced or not, there is no indicator of this. 
Here is my txid from Bittrex:
0xd75d54ac5e07e6bf518e0524679ae31a9ddfcf22c38935f690195eef9089a073

Please contact me if you need any more info. It is quite a bit of money so I would really appreciate help with this.

**Comment by splix** [comment]
If I understand correctly you are not using Emerald Wallet, but Bittrex and Binance, right? Also, as I see that transaction was included into blockchain, so everything went good, regardless the wallet you've used for it. 

It happens very often when an cryptocurrency exchange is not updating your trading balance for a quite long time after transfer to deposit address. If you face such issue you need to contact support of Binance to resolve the issue.

**Comment by PandaHanda** [comment]
Hi,

This case is NOT closed and this issue is NOT solved, not even remotely
close. The problem is NOT with the exchange, as I sent the ETC to the
wallet from BOTH Bittrex and Binance. The ETC is not showing in the wallet.
The chances of both Bittrex and Binance having issues at the same time are
pretty small, especially since I have never had issues using them before.
How do you sync this wallet. The last time I had issues like this the
wallet wasn't synced. However with this Emerald wallet there is no
indicator that shows if it is synced. Can you PLEASE reopen this case, it
is not closed not even close.

**Comment by PandaHanda** [comment]
I sent ETC from Binance to my Emerald wallet, and ETC from Bittrex to my Emerald wallet.

**Comment by splix** [comment]
What type of connection do you use? Remote or local?

**Comment by PandaHanda** [comment]
Do you mean the internet connection? I assume local

**Comment by splix** [comment]
Can you please provide a screenshot of top right corner of the running app? Which includes type of connection and current block

**Comment by PandaHanda** [comment]
[
![etc wallet](https://user-images.githubusercontent.com/35880520/35487001-73334442-0444-11e8-8d82-2e2bf3b3f4c3.jpeg)
](url)

**Comment by splix** [comment]
Right, you're using local full node. Which is on block 48563 right now. Transaction you're referring to is on block 5279561, so you need to wait until remaining 5230998 will be synchronised. It can't show transactions from blocks that are not yet loaded into your node.

**Comment by PandaHanda** [comment]
When will this happen? There is no indicator on the remaining time. Is it
updating in the background without showing? Do I need to leave it open?

Thanks so much, I can finally breathe again.

**Comment by developerkevin** [comment]
Your transaction is in block #5279561 - so you will have to either wait patiently until the node on your wallet (the thing at the top right of the screen that has a green line) is completely synced up to block #5279562 **or** click on the top right corner and click remote node then choose epool.io or gastracker.io. This should connect your wallet and sync quickly, and your balance will be shown. 😃 

Emerald Wallet comes with the options to use a full local node or a remote node by epool and gastracker. You chose full node and have to completely sync the chain. You can always check the status on http://gastracker.io 

I am also on a Mac and have zero issues. Also if you could, from now on please use https://forum.ethereumclassic.org/c/help-me or ETC Discord for issues unrelated to ETC development. Thanks. 👍
