### ISSUE TITLE
Prevent promotion of insecure tokens. `Approve` excluding.

### ISSUE THREAD

**Issue by Dexaran** [ethereumproject/emerald-wallet#46]
As I read in [development update](https://www.etcdevteam.com/blog/devupdate/2017-04-10.html) development of supporting `ERC20 approve` is officially going on in Emerald Wallet.

I want to pay for your attention that `approve` is insecure.

`approve` vulnerability was already described [here](https://drive.google.com/file/d/0ByMtMw2hul0EN3NCaVFHSFdxRzA/view) on EDCON.

Also `approve` and `transferFrom` method usage is considered incorrect from a logical point of view because of its leading to money losses.

You can watch result of this on Ethereum and not repeat their mistakes.

There is already about $13000 lost and this amount is growing each day!
I've already wrote an article about this fact and you can browse it [here on reddit](https://www.reddit.com/r/ethereum/comments/60ql37/attention_be_careful_using_ethereum_tokens/).

I did a lot of research abount tokens and developed a new ERC23 token interface that can prevent such accidents.

If we don't want to officially promote, confirm and support development of insecure tokens that is leading to money losses, we need to remove `approve` function support from Emerald Wallet as there is an alternative way to design secure tokens.

**Comment by splix** [comment]
This wallet is for end users, not developers. So we can't tell them _"please reimplement your token in different way"_

If user has ERC20 token we _MUST_ allow it to use.

**Comment by Dexaran** [comment]
There is *NO ERC20 tokens on ETC * so there is no need to implement their interface.
There is also no need to start producing them!
I think the best solution of the problem that I described will be to recommend *never use ERC20 tokens, don't start to make them on ETC. Watch ETH - they are losing money. ETC is better - there is no such shit on ETC.*

**Comment by splix** [comment]
I understand your concerns, but "producing or not" is unrelated to wallet. You should talk to token developers about that

**Comment by splix** [comment]
@Dexaran wallet can support _both_ ERC20 and ERC23 w/o any problem, I don't see any conflict

**Comment by Dexaran** [comment]
Of course it is supporting ERC23 if it is supporting ERC20. They are compatible.

I know that its mostly token developers decision what standard to use.
But there need to be at least a warning message about: " ERC20 can cause problems. Approve can cause problems. Use it at your own risk. "

There is no need to verify is ERC20 secure or not. $13000 are already lost. Its a fact.

**Comment by splix** [comment]
any contract can cause problem

**Comment by Dexaran** [comment]
Problem with ERC20 contracts is global enough to try to solve it.
People are losing money.
