### ISSUE TITLE
http://localhost:1920/ net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by kimisan** [ethereumproject/emerald-wallet#47]
version Ethereum Classic Geth 3.3.0

After npm run start, i have checked the JS console.
And got the message,
http://localhost:1920/ net::ERR_CONNECTION_REFUSED
I have added a --rpc to the geth
But i am not why still get this err message.

**Comment by splix** [comment]
It expects Emerald Connector on that port, see the project at https://github.com/ethereumproject/emerald-rs

**Comment by kimisan** [comment]
Thanks!
Already synced.
Great Design !

**Comment by splix** [comment]
thanks :) we didn't even start with real design, just making a prototype now. will add a cool design after that
