### ISSUE TITLE
Batch multiple RPC requests

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#475]
Currently it slows down UI and network when a user has 10+ addresses in a wallet, for each of them there're multiple requests for balance of every token, transaction history, etc. To mitigate the issue let's batch such requests. 

Let's make two api functions, a standard one with direct call, and another one which will buffer requests into a batch call (JSON RPC batch operation) and execute it once 100ms, parse results and resolve original promises one by one.

```
-> call 1 -> [a]
-> call 2 -> [a, b]
-> call 3 -> [a, b, c]
...
100ms -> JSON RPC batch -> resolve a -> resolve b -> resolve c
```

**Comment by gagarin55** [comment]
We have such function already https://github.com/ethereumproject/emerald-js/blob/master/src/rpc/jsonrpc.js#L83, some functionality should be refactored in wallet

**Comment by gagarin55** [comment]
I've written the idea described above as feature for request manager - https://github.com/ethereumproject/emerald-js/issues/36
