### ISSUE TITLE
Missing transaction can be solved by using ETCChain, dropping support for buggy gastracker.io API

### ISSUE THREAD

**Issue by pcdinh** [ethereumproject/emerald-wallet#476]
Hi,

I filled a bug report here regarding to gastracker issues https://github.com/ethereumproject/explorer/issues/77

Full correct transaction history by account can be retrieved by using https://etcchain.com/api/ which works smoothly

Regards,

Dinh

**Comment by splix** [comment]
Can you please elaborate it a little? what exactly doesn't work and what are you missing?

**Comment by pcdinh** [comment]
@splix I reported missing transactions in Emerald here (screenshot included)

https://github.com/ethereumproject/emerald-wallet/issues/473

Another screenshot taken with Emerald 0.8.1 RC2 (the latest)

https://i.imgur.com/H62Ey3P.png

In short I think that Emerald is unable to list transactions by account because it receives no data from gastracker.io and epool.io which have a bug.

**Comment by splix** [comment]
no, it doesn't use their apis
