### ISSUE TITLE
deposit not receive

### ISSUE THREAD

**Issue by ffsaik** [ethereumproject/emerald-wallet#482]
Did deposit, on wallet 0xe40fe20fad5e3067a19f01858a42b6ba0b63c174(hash 0xb8f6882d5c0bb4a0b882b46fa2e9e743d427b32efa02396149de49afa01cfd08) , already more that 500 confirmations, but balance still empty, please resove it

**Comment by splix** [comment]
Emerald Wallet is not affiliated with any of crypto exchanges and has no ability to resolve such issues. You need to contact a services you're depositing to and ask them to resolve it, nobody except them can help.

**Comment by ffsaik** [comment]
так я пополнил свой Emerald Wallet, я на него перевел Ethereum Classic с биржы Bittrex, в блокчейне эту транзакцию видно и подтверждений уже более 1000, а кошелек до сиз пор пуст. Куда мне писать тогда с этой проблемой?

**Comment by splix** [comment]
"_deposit_" is usually used in cryptoexchange context, so it looked like you sent from Emerald to an Exchange.

If you don't see updated balance in your wallet make sure your chain is fully synchronized. It takes more than a week to synchronize full blockchain on a standard computer with SSD. Another option would be switching to a remote node, provide by epool or gastracker. You can select them in top right corner.

**Comment by developerkevin** [comment]
@spix it seems there’s a lot of issues related to users and exchanges not Emerald. Maybe we should think about putting out a guide for emerald in the future?

**Comment by TomaszWaszczyk** [comment]
I can prepare the guide for Emerald. If you have an idea what should I
describe, let me know.

11.02.2018 23:26 "Kevin @classic_kevin" <notifications@github.com>
napisał(a):
