### ISSUE TITLE
0 ETC Account balance issue

### ISSUE THREAD

**Issue by SylvainGleye** [ethereumproject/emerald-wallet#498]
Dear all, 
I made my first ETC withdraw from kraken to my Emerald Wallet account 3 days ago and my Emerald wallet account is 0.

someone could help me to display the correct balance?
![2018_02_20_etc form kraken](https://user-images.githubusercontent.com/36810718/36639501-0d6dc446-1a62-11e8-923b-a4dae23aa286.png)
![2018_02_20_etc emerald balance](https://user-images.githubusercontent.com/36810718/36639506-0fc77430-1a62-11e8-83f0-d87abbd5a3b6.png)

Thank you very much.
Sylvain GLEYE

**Comment by gagarin55** [comment]
Your full node is still syncing (as I see on block # 1 213 575)  Balances will be updated after full synchronization

**Comment by SylvainGleye** [comment]
Dear,
thank you very much for this information.
Today the wallet was open all day and all night and the account is always 0
ETC.
How long will it take to download the full bocks?
I can se by now 1 730 249 blocks.

Than you very much,
Sylvain GLEYE


2018-02-27 1:17 GMT+11:00 gagarin55 <notifications@github.com>:

**Comment by splix** [comment]
It usually takes more than a week to do a full sync on a modern hardware

**Comment by SylvainGleye** [comment]
Thank you very uche for this information.
best regards,
Sylvain

2018-03-01 1:51 GMT+11:00 Igor Artamonov <notifications@github.com>:
