### ISSUE TITLE
no screen to import account

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#5]
After clicking "import json" on account creation screen, it should show a new form with upload field. On click "upload" send data to the connector, and redirect user to accounts screen

**Comment by splix** [comment]
Do after #4

**Comment by elaineo** [comment]
Is this JSON file Encrypted in Mist/Geth Format, or plain unencrypted JSON keystore?

**Comment by dulanov** [comment]
it is very dangerous to store locally and to send plain unexcrypted JSON keys, we are starting with default variant - JSON file encrypted in Mist/Geth format.

**Comment by elaineo** [comment]
#21
