### ISSUE TITLE
can't build project

### ISSUE THREAD

**Issue by caochao** [ethereumproject/emerald-wallet#504]
![qq 20180227220134](https://user-images.githubusercontent.com/1911170/36733081-78be339e-1c0a-11e8-849c-2b340e55863c.jpg)

**Comment by gagarin55** [comment]
Try delete node_modules folder and run `npm install` again

**Comment by redcom** [comment]
The other fix  is to use 
```
import { EtcLogo } from 'emerald-js-ui/lib/icons2';
```

**Comment by caochao** [comment]
thanks, it works

**Comment by caochao** [comment]
it seems emerald-js-ui repo has update and my local node_modules is old

**Comment by gagarin55** [comment]
Yes, sorry for that, but libs are under heavy development.
