### ISSUE TITLE
Invalid length for hex string in `send_Transaction` JSON RPC call 

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#54]
There is invalid length of fields ( hex string is not modulo of 2) inside JSON object of transaction.
`gasPrice` and `value` have odd length.

`[{"from": "0x2a191e0a15dbcfaf30fa0548ed189bc77f3284ae",
   "gas": "0x5208",
   "gasPrice": "0x2540be400", 
    "to": "0x004a301af857a471b9bde4fcc4654dba4f38272a",
    "value": "0xde0b6b3a76400"}]"`

**Comment by elaineo** [comment]
PR #55
