### ISSUE TITLE
Return passphrase inside json for rpc 

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#62]
json_rpc lib lacks support for `Authorization` header, so wee need to return 
passphrase inside `JSON`.

[https://github.com/ethereumproject/emerald-wallet/issues/42](url)

**Comment by elaineo** [comment]
Also related: #43 . Is this okay, @dulanov ?

**Comment by dulanov** [comment]
Yes, we have a problem with another library to properly process `Authorization` head and in near future we will switch to ffi, so it's not a problem now to send a password as a plain text in json.

**Comment by elaineo** [comment]
The current implementation already sends the passphrase inside `JSON` so nothing needs to be updated here, right?

**Comment by dulanov** [comment]
Please remove `Authorization` header completely, wallet CORS requests failed now.

**Comment by elaineo** [comment]
Ok, updated #63
