### ISSUE TITLE
Need to replace blob:http mock in rpc call `backend_importWallet`

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#66]
We need to receive account file in `JSON` format to process it in emerald-rs.
Currently there is blob:http mock that emerald-rs can't handle.

**Comment by elaineo** [comment]
Do you need filename, for the timestamp? eg `UTC--2017-05-28T06-24-24Z--cfdaa4e4-dddd-4444-ffff-f00f00f00f00`

**Comment by r8d8** [comment]
Yeap, I can't extract it from keyfile internals.

**Comment by elaineo** [comment]
okay, i will add filename, name, and description to the JSON object.

**Comment by dulanov** [comment]
I don't know it's a connector or wallet error, anyway, after submit click came error:

![image](https://cloud.githubusercontent.com/assets/39793/26226492/c53a29f8-3c2c-11e7-9a64-244bedaee9d2.png)

pointed to:

```

function defaultTitleFormatter(options) {
  var timestamp = options.timestamp,
      duration = options.duration;


  return function (action, time, took) {
    var parts = ['action'];

    if (timestamp) parts.push('@ ' + time);
>>>    parts.push(String(action.type));
    if (duration) parts.push('(in ' + took.toFixed(2) + ' ms)');

    return parts.join(' ');
  };
}
```

**Comment by dulanov** [comment]
Keyfile: [UTC--2017-05-18T16-19-43.zip](https://github.com/ethereumproject/emerald-wallet/files/1012616/UTC--2017-05-18T16-19-43.zip)

**Comment by dulanov** [comment]
Additionally, maybe could be helpful: ![image](https://cloud.githubusercontent.com/assets/39793/26226620/67a211ce-3c2d-11e7-80dc-8bc4c4fb0189.png)

**Comment by dulanov** [comment]
@elaineo great job, thanks a lot, but there is a little problem with request:

```
│TRACE:jsonrpc_core::io: Request: {"jsonrpc":"2.0","method":"backend_importWallet","params":{"id":"00c6984c-948a-40ce-a756-21f893295673","address":"6a7cc99d37e28059306ce7f14ad99d671e7db6c0","crypto":{"cipher":"aes-128-ctr","ciphertext":"870f4b457e3a16e304e09550d3780835fc8810166d21ef9c150b0901d0f2b61a","cipherparams":{"iv":"c2d97d7e0c254704ea4219e04d2da791"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"f704fe32ef4a0375ab73f760d2fef02942fc0b304de5cee95b3ff4ff0│a1af636"},"mac":"2a36649bed49abd952d260f496119eb80a4cbc84144c9b958d874f585dc26aa9"},"version":3,"filename":"UTC--2017-05-18T16-19-43.3412674Z--6a7cc99d37e28059306ce7f14ad99d671e7db6c0"},"id":19}.
```

Here params should be always a JSON list, not an objects:

```
"params": [..]
```

**Comment by dulanov** [comment]
hm, it can be wrong, I will check it tomorrow - http://www.jsonrpc.org/specification

**Comment by elaineo** [comment]
The other `params` have been in JSON list format, so we should probably do that for consistency (although I'm not sure why they are always a JSON list).

**Comment by r8d8** [comment]
@elaineo can you please move `filename` on one level up. 
I mean, se need to have such structure:
![json](https://cloud.githubusercontent.com/assets/8018746/26310122/bdc73aee-3f10-11e7-948c-793a8c99239f.png)

**Comment by r8d8** [comment]
And also , please, move `description` and `name` one level up.
like this:
![json](https://cloud.githubusercontent.com/assets/8018746/26317235/de8e06ba-3f27-11e7-8eef-ece106bb0402.png)
