### ISSUE TITLE
Doesn't support tokens

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#7]
Add tokens:

* [x] #8 card with list of existing tokens (name, id, total coins)
* [x] #9 add token form

**Comment by elaineo** [comment]
Mist has [hard-coded functions](https://github.com/ethereum/mist/blob/68a6a335fb4a2f10dd2909959bd78ac578a45695/interface/client/lib/signatures.js) for interacting with standard contract ABIs. Will we have something like this on the client side, or is this connector's job?

**Comment by splix** [comment]
for token operations (transfer/approve/etc) use hardcoded functions. connector going to store list of token contracts (addr, abi, extra details)

**Comment by elaineo** [comment]
I see that you have 
      `const tokenSupplyId = "0x18160ddd";
        const decimalsId =    "0x313ce567";
        const symbolId =      "0x95d89b41";
        const nameId =        "0x06fdde03";`
all hardcoded in tokenActions. Only `tokenSupply` is part of ERC20. Should the wallet user be able to enter a name/symbol/decimal if the token contract does not support it?

**Comment by splix** [comment]
Yes, I think we should allow user to override this values. I'll create another issues for that

**Comment by splix** [comment]
#26
