### ISSUE TITLE
Network status isn't updated automatically

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#71]
Changes only by manual refresh, not automatically in background:

![image](https://cloud.githubusercontent.com/assets/39793/26223517/aba37638-3c1e-11e7-8619-5a8bb9431f04.png)

**Comment by elaineo** [comment]
It is automatically refreshing... cannot reproduce this bug. 

see `src/store/store.js`:

`
    setTimeout(() => store.dispatch(loadSyncing()), 3000); // check for syncing
    setTimeout(() => store.dispatch(loadSyncing()), 30000); // double check for syncing after 30 seconds
`

**Comment by dulanov** [comment]
@elaineo how you tried to reproduce it? Normally I make `npm run build` and then open `/build/index.html` in Chrome, that's right?

**Comment by elaineo** [comment]
Yes, that works! In the dev console, do you see a bunch of `NETWORK/SYNCING` actions? Each one should update the network status. Connector and node must also be running at the same time.

<img width="913" alt="screen shot 2017-05-25 at 7 08 04 am" src="https://cloud.githubusercontent.com/assets/2349487/26453569/0b06b226-4119-11e7-8151-4ec430997187.png">

**Comment by dulanov** [comment]
`NETWORK/SYNCING` fails for me:

![image](https://cloud.githubusercontent.com/assets/39793/26472497/af14a912-41a6-11e7-8702-5cd841393366.png)

![image](https://cloud.githubusercontent.com/assets/39793/26472520/cfcdef4c-41a6-11e7-8b0c-e47012bdeb9d.png)

```
TRACE:jsonrpc_core::io: Request: {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":9}.
INFO:reqwest::client: Request: Post http://127.0.0.1:8545/
INFO:reqwest::response: Response: '200 OK' for http://127.0.0.1:8545/
DEBUG:jsonrpc_core::io: Response: Some("{\"jsonrpc\":\"2.0\",\"result\":false,\"id\":9}").
```

**Comment by dulanov** [comment]
![image](https://cloud.githubusercontent.com/assets/39793/26472599/2a619abc-41a7-11e7-97da-8aa95bb1fef1.png)

**Comment by dulanov** [comment]
So, I think the problem with `false` `eth_syncing` RPC call, so this issue isn't actual any more.
