### ISSUE TITLE
Token icon isn't aligned horizontally

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#73]
![image](https://cloud.githubusercontent.com/assets/39793/26224211/a1488d7e-3c21-11e7-8774-76168127cbee.png)

**Comment by dulanov** [comment]
Probably also:

![image](https://cloud.githubusercontent.com/assets/39793/26224308/027e9994-3c22-11e7-8a45-a801a5b8c356.png)

**Comment by elaineo** [comment]
icons removed :) https://github.com/ethereumproject/emerald-wallet/issues/252
