### ISSUE TITLE
Alternative wallet icons (for discussion only)

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#75]
Current icons:

![image](https://cloud.githubusercontent.com/assets/39793/26224895/cd64b182-3c24-11e7-94bc-7c6ef8f58201.png)

Why home is a face? Why a contract is a text? Why network is a motorcycle?

My, IMHO, personal suggestions:

For home:

![image](https://cloud.githubusercontent.com/assets/39793/26224931/05c750c0-3c25-11e7-9a4f-a97a1336358a.png)

For address book (just alternatives):

![image](https://cloud.githubusercontent.com/assets/39793/26224963/36c282da-3c25-11e7-9af6-48ad168ba825.png)

![image](https://cloud.githubusercontent.com/assets/39793/26224985/4db23152-3c25-11e7-9a5a-3e9b1850fce8.png)

For contract:

![image](https://cloud.githubusercontent.com/assets/39793/26224941/11e64050-3c25-11e7-8fc7-49796a0a70a2.png)

For network selection:

![image](https://cloud.githubusercontent.com/assets/39793/26225041/901c0266-3c25-11e7-8df3-afe13d50f436.png)

![image](https://cloud.githubusercontent.com/assets/39793/26225120/fc7f41a2-3c25-11e7-9fee-f46ff48d4002.png)

![image](https://cloud.githubusercontent.com/assets/39793/26225175/33611b64-3c26-11e7-8a8f-65ba57855231.png)

For token (coin): nothing found ;(

**Comment by whilei** [comment]
token ?
![screen shot 2017-05-18 at 17 05 39](https://cloud.githubusercontent.com/assets/10228550/26225369/7adf256a-3bec-11e7-90ed-117f08768bbe.png)

**Comment by whilei** [comment]
and the 'link' icon makes sense to me for token/+network, but may be confusing since its kind of ubiquitous..
![screen shot 2017-05-18 at 17 03 49](https://cloud.githubusercontent.com/assets/10228550/26225424/bb4e98b0-3bec-11e7-8e16-456d9712adb2.png)

**Comment by splix** [comment]
That's just a prototype at the moment. We'll make a good design, don't worry :) I have a designer working on this stuff, just not ready yet

**Comment by elaineo** [comment]
hahaha, i chose most of the icons randomly as placeholders. Don't take them too seriously :)

**Comment by dulanov** [comment]
@elaineo I am going to switch back to coding, end of test session, finally ;)

**Comment by elaineo** [comment]
addressed heer: https://github.com/ethereumproject/emerald-wallet/issues/252
