### ISSUE TITLE
Incorrect chain label after page reload

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#79]
Currently in wallet if one selects `testnet`, and reloads page in browser, we lossing correct chain specifier (after reload it allways `MAINNET`).
@dulanov , should we add new rpc call for chain syncing ?

**Comment by elaineo** [comment]
@r8d8 Yeah, the network state needs to come from the connector. We can either add new rpc call, or include the information with `eth_syncing` or `eth_blockNumber`. Let me know what you prefer.
