### ISSUE TITLE
Doesn't display list of installed tokens

### ISSUE THREAD

**Issue by splix** [ethereumproject/emerald-wallet#8]
Add a card with tokens to main screen, similar to accounts card. 

Display:
 * name
 * address
 * code
 * total coins

**Comment by splix** [comment]
rel #7

**Comment by elaineo** [comment]
is "total coins" the total owned across all accountIds, or "total coins" issued by token contract?

**Comment by splix** [comment]
total for contract

**Comment by elaineo** [comment]
PR #23
