### ISSUE TITLE
`sendTransaction` rpc call stucks on trace call stage

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#87]
While user trying to sent transaction, process stuck on traceCall with highlighted `Account` field. It's not obvious what goes wrong:

![trace](https://cloud.githubusercontent.com/assets/8018746/26542400/c58800f6-446a-11e7-937e-e9232501a3f5.png)

**Comment by elaineo** [comment]
`Invalid Transaction` usually means your account has insufficient balance for the transaction. I can try to make it more informative. Come to think of it, the page really should display the account balance.

**Comment by dulanov** [comment]
@elaineo the problem not with the balance, someting goes wrong with `eth_callTrace` result processing.

**Comment by elaineo** [comment]
@dulanov I can't reproduce except for in the case of insufficient balance, but #92 should add more information about the error.

**Comment by elaineo** [comment]
Shoot. I had been testing with parity's `trace_call` instead of geth's `eth_traceCall`. 
they return different formats, but the wallet should support both.
https://github.com/ethereumproject/emerald-rs/issues/30#issuecomment-291987132

**Comment by elaineo** [comment]
fixed for now, should be addressed later on by node or connector 
https://github.com/ethereumproject/emerald-rs/issues/97
