### ISSUE TITLE
Why we use `eth_traceCall` instead of `eth_estimateGas`?

### ISSUE THREAD

**Issue by dulanov** [ethereumproject/emerald-wallet#90]
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_estimategas

**Comment by dulanov** [comment]
Isaak said: w/r/t `traceCall` vs. `estimateGas` ->
`traceCall` can be used for an arbitrary block number and will also return `returnValue`, while
`estimateGas` uses `PendingBlockNumber` and just returns gas

**Comment by elaineo** [comment]
Yes, also contracts can change their behavior based on the order of different tx's submitted to it.
Issue duplicated here: https://github.com/ethereumproject/emerald-wallet/issues/32
