### ISSUE TITLE
List of account corrupted

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/emerald-wallet#93]
Wallet can't show proper account details in address book.
![img_20170601_090305](https://cloud.githubusercontent.com/assets/8018746/26665267/f7e7b644-4687-11e7-9bed-6555b5a2f01c.jpg)

**Comment by elaineo** [comment]
Right now the account list assumes this format from the connector:

` {"result": [{
                "address":"0x00000000000000000000000000000b74068b0E49",
                "name": "hello"},
                {"address":"0x00000000000000000000000000000b000000",
                "name":"bbee"}
]}`

Since account has been updated to save names. but i think it is not updated yet in emerald-rs. Is this okay?

**Comment by r8d8** [comment]
Ok, I will fix it in emerald-rs

**Comment by r8d8** [comment]
Wallet can't handle empty names
![img_20170601_094726](https://cloud.githubusercontent.com/assets/8018746/26666181/1af7cd9e-468e-11e7-8082-6581962950e8.jpg)
