### ISSUE TITLE
Add "alert" component for UI notifications

### ISSUE THREAD

**Issue by whilei** [ethereumproject/emerald-wallet#95]
__For example:__
- Your transaction has been added! 👍 
- Your new account has successfully been created! 👍 
- You're not connected to a network 🤒 

__Specs:__
Should have a consistent layout, likely floating with high `z-index` in a corner or something. 

Component should have parameters for:
- alert message, ie "Transaction successfully processed."
- help message, ie "Click here to view your transaction."
- type ['success', 'error', 'info', 'warning']
- duration

UI should:
- display alert message in larger font than help message, and on top
- help message should give instructions about possible next steps
- type should correlate to background color (green, red, blue,...)
- duration should determine how long before message auto-disappears, maybe with `0` for never
- should have an `X` button to hide

Make sense? Assuming it hasn't been done yet and/or its job hasn't already been filled in some way I haven't seen (?)

**Comment by splix** [comment]
rel #10

**Comment by elaineo** [comment]
Should we have the designer implement this in the design sketch? I can add a modal dialog or snackbar, but I find popups kind of annoying and prefer something like the read dot over an app icon telling you there are notifications.

**Comment by splix** [comment]
Design is on the way
